# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-IndexParser
version:      0.5
version_from: lib/WWW/IndexParser.pm
installdirs:  site
requires:
    HTML::Parser:                  3
    LWP:                           5.6
    Time::Local:                   1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
